server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: smsModule
          uri: lb://SMS-SERVICE
          predicates:
            - Path=/sms/**
        - id: pushModule
          uri: lb://PUSH-SERVICE
          predicates:
            - Path=/push/**
        - id: emailModule
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**

